# Generated by Django 2.2 on 2020-12-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdtBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_brand_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='CdtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=4, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='CdtVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_vendor', models.CharField(max_length=50, verbose_name='Vendor')),
                ('nm_phone_number_vendor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number')),
                ('tx_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='TdtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_product_name', models.CharField(max_length=75, verbose_name='Product Name')),
                ('tx_description', models.TextField(max_length=300, verbose_name='Description')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtBrand')),
                ('id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtVendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='TdtSkuProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=75, verbose_name='Sku')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_form.TdtProduct')),
                ('id_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_form.CdtSize')),
            ],
            options={
                'verbose_name': 'SKU Product',
                'verbose_name_plural': 'SKU Products',
            },
        ),
    ]
