# Generated by Django 2.2 on 2020-12-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdtColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='CdtProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_url_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('bl_primary', models.BooleanField(default=False, verbose_name='Primary')),
            ],
        ),
        migrations.RemoveField(
            model_name='tdtskuproduct',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='tdtskuproduct',
            name='id_size',
        ),
        migrations.DeleteModel(
            name='CdtSize',
        ),
        migrations.DeleteModel(
            name='TdtSkuProduct',
        ),
        migrations.AddField(
            model_name='cdtcolor',
            name='id_photo',
            field=models.ManyToManyField(to='app_form.CdtProductPhoto'),
        ),
        migrations.AddField(
            model_name='cdtcolor',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.TdtProduct'),
        ),
    ]
