# Generated by Django 2.2 on 2020-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_auto_20201205_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtproductphoto',
            name='tx_url_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo', verbose_name='Photo'),
        ),
    ]
