# Generated by Django 2.2 on 2020-12-08 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_auto_20201205_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=4, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='TdtSkuProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=75, verbose_name='Sku')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_form.TdtProduct')),
                ('id_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_form.CdtSize')),
            ],
            options={
                'verbose_name': 'SKU Product',
                'verbose_name_plural': 'SKU Products',
            },
        ),
    ]
