# Generated by Django 2.2 on 2020-12-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_cdtsize_tdtskuproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtcolor',
            name='id_photo',
        ),
        migrations.AddField(
            model_name='cdtproductphoto',
            name='id_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtColor'),
        ),
        migrations.RemoveField(
            model_name='cdtcolor',
            name='id_product',
        ),
        migrations.AddField(
            model_name='cdtcolor',
            name='id_product',
            field=models.ManyToManyField(to='app_form.TdtProduct'),
        ),
    ]
