# Generated by Django 2.2 on 2020-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0006_auto_20201208_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtcolor',
            name='id_product',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_color',
            field=models.ManyToManyField(to='app_form.CdtColor'),
        ),
    ]
