# Generated by Django 2.2 on 2020-12-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0007_auto_20201208_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtproductphoto',
            name='id_color',
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='id_color',
        ),
        migrations.CreateModel(
            name='CdtProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_form.CdtColor')),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_form.TdtProduct')),
            ],
        ),
        migrations.AddField(
            model_name='cdtproductphoto',
            name='id_product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtProductColor'),
        ),
    ]
