# Generated by Django 2.2 on 2020-12-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0009_auto_20201208_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdtproductcolor',
            options={'verbose_name': 'Match Product', 'verbose_name_plural': 'Match Products'},
        ),
    ]
