# Generated by Django 2.2 on 2020-12-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0012_auto_20201208_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdtskuproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='tdtskuproduct',
            name='sku',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
