# Generated by Django 2.2 on 2020-12-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0013_auto_20201208_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdtskuproduct',
            name='sku',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
