# Generated by Django 2.2 on 2020-12-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0014_auto_20201208_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CdtCategoryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_category_person', models.CharField(max_length=50, verbose_name='Category Person')),
            ],
            options={
                'verbose_name': 'Category Person',
                'verbose_name_plural': 'Categories Persons',
            },
        ),
        migrations.CreateModel(
            name='CdtSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_subcategory_name', models.CharField(max_length=50, verbose_name='Subcategory')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtCategory')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.AddField(
            model_name='cdtcategory',
            name='id_category_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtCategoryPerson'),
        ),
        migrations.AddField(
            model_name='cdtsize',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_form.CdtCategory'),
        ),
    ]
