# Generated by Django 2.2 on 2020-12-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0015_auto_20201211_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdtproduct',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtCategory'),
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_category_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtCategoryPerson'),
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_form.CdtSubcategory'),
        ),
    ]
