# Generated by Django 2.2 on 2020-12-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0016_auto_20201211_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtproductcolor',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_form.TdtProduct'),
        ),
    ]
